<?php

return [

    'SMS_USERNAME' => env('SMS_USERNAME', ''),
    'SMS_PASSWORD' => env('SMS_PASSWORD', ''),
    'SMS_SENDER_ID' => env('SMS_SENDER_ID', ''),
    'SMS_URL' => env('SMS_URL', ''),
    'SMS_EXTRA_URL_APPEND' =>env('SMS_EXTRA_URL_APPEND', ''),
    'SMS_PRIORITY'  =>env('SMS_PRIORITY', ''),
    'SMS_TYPE'  =>env('SMS_TYPE', ''),

    'SMS_URL_USERNAME_PLACEHOLDER' => env('SMS_URL_USERNAME_PLACEHOLDER', ':USERNAME'),
    'SMS_URL_PASSWORD_PLACEHOLDER' => env('SMS_URL_PASSWORD_PLACEHOLDER', ':PASSWORD'),
    'SMS_URL_SENDER_ID_PLACEHOLDER' => env('SMS_URL_SENDER_ID_PLACEHOLDER', ':SENDERID'),
    'SMS_URL_MOBILE_NO_PLACEHOLDER' => env('SMS_URL_MOBILE_NO_PLACEHOLDER', ':MOBILENO'),
    'SMS_URL_MESSAGE_PLACEHOLDER' => env('SMS_URL_MESSAGE_PLACEHOLDER', ':MESSAGE'),
    'SMS_URL_PRIORITY_PLACEHOLDER' => env('SMS_URL_PRIORITY_PLACEHOLDER', ':PRIORITY'),
    'SMS_URL_TYPE_PLACEHOLDER' => env('SMS_URL_TYPE_PLACEHOLDER', ':TYPE'),


];

